name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.2.6 # This is the action
        with:
          heroku_api_key: "24698d7f-51c3-4379-85c2-02be429a45b9"
          heroku_app_name: "connect4-1" #Must be unique in Heroku
          heroku_email: "nilakhesourabh@gmail.com"
